# Generated by Django 5.1.5 on 2025-01-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_department_remove_userprofile_aadhar_no_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.department', to_field='dep_name'),
        ),
    ]
