# Generated by Django 5.1.5 on 2025-01-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_department_dep_name_alter_student_stu_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_name', models.CharField(choices=[('Tata', 'Tata'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_dep',
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_fuel', models.CharField(choices=[('Petro', 'Petrol'), ('Desail', 'Desail'), ('Cng', 'Cng')], max_length=50)),
                ('V_name', models.ManyToManyField(to='App.vehical')),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
