# Generated by Django 5.1.4 on 2025-01-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Description', models.CharField(max_length=50)),
                ('Contect', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Volume', models.IntegerField()),
                ('Education', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('Image', models.ImageField(upload_to='')),
                ('Resume', models.FileField(upload_to='')),
                ('Password', models.CharField(max_length=50)),
                ('Con_Password', models.CharField(max_length=50)),
            ],
        ),
    ]
