# Generated by Django 5.1.4 on 2025-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Education',
            field=models.CharField(max_length=50),
        ),
    ]
